In [5]:
import sys
sys.path.append("../src/")
import transform
import utils_test
import numpy as np

In [11]:
N = 3
T = utils_test.generate_low_rank_tensor( (N,N), 10, seed=None)
T = T / np.sum(T)

In [12]:
T

array([[0.10392429, 0.11319391, 0.13027214],
       [0.10692486, 0.12675552, 0.13910519],
       [0.08267076, 0.08632422, 0.11082911]])

In [16]:
theta = transform.theta_from_prob(T, chi="Tsallis", q=1)
theta

array([[-2.26409262,  0.08543973,  0.14052322],
       [ 0.02846368,  0.08469409, -0.04755299],
       [-0.25726037, -0.12688956,  0.15690904]])

In [18]:
eta = transform.eta_from_prob(T, chi="Tsallis", q=1)
eta

array([[1.        , 0.70648009, 0.38020644],
       [0.65260966, 0.46301404, 0.2499343 ],
       [0.2798241 , 0.19715334, 0.11082911]])

In [19]:
T = utils_test.generate_low_rank_tensor( (N,N), 1, seed=None)
T = T / np.sum(T)

In [21]:
theta = transform.theta_from_prob(T, chi="Tsallis", q=1)
theta

array([[-1.02326480e+00, -1.93550025e+00,  2.48139363e-01],
       [-2.44688459e-01,  0.00000000e+00,  4.44089210e-16],
       [-9.26535025e-01,  2.22044605e-16,  0.00000000e+00]])