In [92]:
from mproject import MBA
from mproject import MBA_LBFGS
import manage_intract
import utils_test
import numpy as np
import importlib
import mask

import importlib
importlib.reload(manage_intract)

<module 'manage_intract' from '/zhome/67/4/218662/papers/AISTATS2025/src/manage_intract.py'>

In [2]:
N = 8
P = utils_test.generate_low_rank_tensor( (N,N,N,N), 10, seed=None)
#P = np.random.rand(N,N,N)
P = P / np.sum(P)
D = np.ndim(P)

#intract = manage_intract.get_m_body_intract(3,D)
intract = [[1, 1, 1, 1], [1, 0, 0, 1, 0, 1], [0, 0, 0, 0], [0]]
Q, theta, eta, his = MBA(P, intract, lr=0.01, Newton=False, max_iter=100, chi="Tsallis", q=1.0, verbose_interval=1, verbose=True, epsilon=0.0, beta=1);

Algorithm settings:
  Optimization method    : Gradient descent
  Cost function          : Tsallis divergence
    q (Tsallis param)    : 1.0
Input Tensor Info:
  Shape of input tensor  : (8, 8, 8, 8)
  Size of input tensor   : 4096
  Number of params       : 175
  Size of FIM            : 175 x 175 = 30625
Active Interactions:
 1-body: [[0], [1], [2], [3]]
 2-body: [[0, 1], [1, 2], [2, 3]]
 3-body: []
 4-body: []
  Iter |   Time |   chi-div(P||Q) |   chi-div(Q||P)
--------------------------------------------------------
     0 |  0.001 |    9.202748e-02 |    8.288947e-02
     1 |  0.002 |    9.132690e-02 |    8.229538e-02
     2 |  0.003 |    9.064195e-02 |    8.171423e-02
     3 |  0.004 |    8.997193e-02 |    8.114545e-02
     4 |  0.004 |    8.931622e-02 |    8.058846e-02
     5 |  0.005 |    8.867423e-02 |    8.004278e-02
     6 |  0.006 |    8.804540e-02 |    7.950792e-02
     7 |  0.007 |    8.742921e-02 |    7.898344e-02
     8 |  0.008 |    8.682518e-02 |    7.846892e-02
     9

In [3]:
Q, theta, eta, his = MBA(P, intract, lr=0.01, Newton=True, max_iter=100, chi="Tsallis", q=1.0, verbose_interval=1, verbose=True, epsilon=0.0, beta=1);

Algorithm settings:
  Optimization method    : Newton's method
  β (scaling factor)     : 1
  ε (stabilizer)         : 0.0
  lr (learning rate)     : 0.01
  Cost function          : Tsallis divergence
    q (Tsallis param)    : 1.0
Input Tensor Info:
  Shape of input tensor  : (8, 8, 8, 8)
  Size of input tensor   : 4096
  Number of params       : 175
  Size of FIM            : 175 x 175 = 30625
Active Interactions:
 1-body: [[0], [1], [2], [3]]
 2-body: [[0, 1], [1, 2], [2, 3]]
 3-body: []
 4-body: []
  Iter |   Time |   chi-div(P||Q) |   chi-div(Q||P)
--------------------------------------------------------
     0 |  0.004 |    1.502170e-02 |    1.457713e-02
     1 |  0.007 |    1.180817e-02 |    1.169999e-02
     2 |  0.010 |    1.173608e-02 |    1.165975e-02
     3 |  0.013 |    1.173497e-02 |    1.165970e-02
     4 |  0.016 |    1.173497e-02 |    1.165970e-02
     4 |  0.016 |    1.173497e-02 |    1.165970e-02
--------------------------------------------------------
Converged afte

In [4]:
_, _, _, _ = MBA_LBFGS(P, intract, max_iter=100, chi="Kani", k=0.1, verbose_interval=10, verbose=True, init="uniform", m_step=False);

Algorithm settings:
  Optimization method    : LBFGS
  Cost function          : Kani divergence
    k (Kani param)       : 0.1
Input Tensor Info:
  Shape of input tensor  : (8, 8, 8, 8)
  Size of input tensor   : 4096
  Number of params       : 175
  Size of FIM            : 175 x 175 = 30625
Active Interactions:
 1-body: [[0], [1], [2], [3]]
 2-body: [[0, 1], [1, 2], [2, 3]]
 3-body: []
 4-body: []
  Iter |   Time |   chi-div(P||Q) |   chi-div(Q||P)
--------------------------------------------------------
     0 |  0.008 |    9.335916e-02 |    8.572208e-02
    10 |  0.037 |    3.471083e-02 |    3.393221e-02
    20 |  0.069 |    2.579823e-02 |    2.547362e-02
    30 |  0.098 |    2.228916e-02 |    2.203504e-02
    40 |  0.129 |    1.989338e-02 |    1.978773e-02
    50 |  0.161 |    1.841078e-02 |    1.822664e-02
    60 |  0.193 |    1.795053e-02 |    1.772636e-02
    70 |  0.225 |    1.747171e-02 |    1.730925e-02
    80 |  0.256 |    1.726688e-02 |    1.712219e-02
    90 |  0.288 |   

In [5]:
N = 3
P = utils_test.generate_low_rank_tensor( (N,N,N,N), 3, seed=None)

#P = np.random.rand(2,3,4)
P = P / np.sum(P)
D = np.ndim(P)
shape = np.shape(P)

intract = manage_intract.get_m_body_intract(2,D)
intract = [[1, 1, 1, 1], [0, 0, 0, 1, 0, 1], [0, 0, 0, 0], [0]]
learn_indices = mproject.get_msk(shape, intract)
non_learn_indices = get_non_learn_indices(shape, learn_indices) 

NameError: name 'mproject' is not defined

In [10]:
_ = MBA_LBFGS(P, intract, max_iter=10000, chi=1, verbose_interval=10, verbose=True, m_step=True);

   [M-step]      0 |  0.001 |    1.761008e-01 |    1.915268e-01
   [M-step]     10 |  0.006 |    2.023067e-02 |    1.979369e-02
   [M-step]     20 |  0.010 |    1.985191e-02 |    1.952275e-02
   [M-step]     30 |  0.014 |    1.986129e-02 |    1.951317e-02
   [M-step]     40 |  0.020 |    1.985668e-02 |    1.951273e-02


In [47]:
learn_indices

array([[1, 0, 0, 0],
       [2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 2],
       [0, 1, 1, 0],
       [0, 1, 2, 0],
       [0, 2, 1, 0],
       [0, 2, 2, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [0, 0, 2, 1],
       [0, 0, 2, 2]])

In [74]:
#N = 
#P = utils_test.generate_low_rank_tensor( (N,N,N,N), 3, seed=None)

#P = np.random.rand(N,N,N,N)
#P = P / np.sum(P)
#D = np.ndim(P)
shape = (30,30,30,30,30)

intract = manage_intract.get_m_body_intract(3,D)

In [78]:
get_learn_indices(shape, intract)

array([[ 1,  0,  0,  0,  0],
       [ 2,  0,  0,  0,  0],
       [ 3,  0,  0,  0,  0],
       ...,
       [29,  0, 29, 27,  0],
       [29,  0, 29, 28,  0],
       [29,  0, 29, 29,  0]], shape=(102718, 5))

In [27]:
MBAe(P, intract)

NameError: name 'msk' is not defined

In [100]:
import mproject
import divergence 
import time
import verbose

importlib.reload(verbose)
from verbose import print_initial_info_em
from verbose import print_initial_info
from verbose import show_verbose
from verbose import show_terminate
importlib.reload(mproject)
from mproject import MBA_LBFGS

from mproject import MBA
import manage_intract
import utils_test
import numpy as np
import importlib
import mask

import importlib
importlib.reload(manage_intract)

def LRA(T, rank, q, max_iter_outer=100, 
        max_iter_inner=100,
        init="random", 
        method="LBFGS",
        lr=0.1, 
        get_cost_dual=True, get_history=True,
        tol_inner=1.0e-8, tol_outer=1.0e-6, epsilon=1.0e-10,
        seed=None, init_inner="uniform", beta=1.0, Newton=True,
        verbose_inner = True,
        verbose_interval_inner = 10,
        verbose_interval_outer = 1,
        confirm_inequality=True, confirm_tightness=True, confirm_optimal_mstep=True,
        use_prev_theta=True
       ):

    history = {"iter":[], "time":[], "loss":[]}

    # Original tensor's dim
    D = np.ndim(T)

    # Shape of low-body tensor Q
    tensor_shape = np.shape(T) + (rank,)
    
    # structure of Interaction in Q
    intract_CP = manage_intract.get_intract_CP(D+1)

    # Obtain the set of learned indices
    # For CP, we need all one-body and 
    # two-body between hidden and visible modes
    msk = mask.get_learn_indices(tensor_shape, intract_CP)
    n_params = len(msk)
    
    chi = "Tsallis"
    if method == "Newton":
        Newton = True
    elif method != "LBFGS":
        Newton = False
    else:
        Newton = "LBFGS"
        
    if verbose:
        print_initial_info_em(rank, q, init, init_inner, use_prev_theta)
        print_initial_info(Newton, lr, beta, epsilon, tensor_shape, n_params, intract_CP, chi, q=q)
    
    ## Randomized initialization 
    ## LRA is a non-convex optimization problem and 
    ## solution depends on R_init.
    R, _, _ = mproject.init_values(tensor_shape, msk, init=init)
    R_prev = np.copy(R) # Just for debuging
    
    ## Marginalization along hidden variable k
    P = np.sum(R, axis=-1)
    
    ## R is a low-body tensor. R has one- and two-body interactions
    ## Q is on the data manifold. After marginalization, it becomes data T
    n_iter = 0

    cost_prev = +np.inf
    cost_dual_prev = +np.inf
    
    start_time = time.time()
    elapsed_time = 0.0
    
    theta_prev = None
    converge = False
    while(n_iter < max_iter_outer + 1):
        ## E-step: projection onto data manifold
        ## Optimal update to minimize D_f[R||Q] for R
        Q = R * (T[..., np.newaxis] / P[..., np.newaxis])
        
        ## For debug
        ## Confirm if the E-step make it tightness D_f[T, P] = D_f[Q, R]
        if confirm_tightness:
            df_TP = divergence.alpha_divergence(T, P, q, avoid_nan=True)
            df_QR = divergence.alpha_divergence(Q, R, q, avoid_nan=True)
            if abs(df_TP - df_QR) > 1.0e-10:
                print(f"No tightness df_TP:{df_TP:10.5f} df_QR:{df_QR:10.5f}")
        
        ## M-step: projection onto model manifold
        ## Optimal update to minimize D_f[R||Q] for Q
        ## This is equivalent to
        ## Optimal update to minimize D_χ[Q||R] for Q 
        if method == "LBFGS":
            R, theta, eta, _ = MBA_LBFGS(Q, intract_CP, max_iter=max_iter_inner,
                             init=init_inner, get_history=False, 
                             get_cost_dual=get_cost_dual, m_step=True,
                             verbose_interval=verbose_interval_inner,
                             theta_0 = theta_prev,
                             chi=chi, q=q, verbose=verbose_inner)
        
        else:
            if method == "Newton":
                Newton = True
            else:
                Newton = False
            R, theta, eta, _ = MBA(Q, intract_CP, max_iter=max_iter_inner,
                             init=init_inner, get_history=False, 
                             lr=lr, beta=beta, epsilon=epsilon, 
                             verbose_interval=verbose_interval_inner,
                             theta_0 = theta_prev,
                             get_cost_dual=get_cost_dual, m_step=True,
                             chi=chi, q=q, Newton=Newton, verbose=verbose_inner)
        
        ## Marginalization along hidden variable k
        P = np.sum(R, axis=-1)

        ## For debug
        ## Confirm if the M-step makes the objective smaller 
        ## i.e., D_f[Q, R] < D_f[Q, Rprev]
        if confirm_optimal_mstep:
            df_QR = divergence.alpha_divergence(Q, R, q, avoid_nan=True)
            df_QRprev = divergence.alpha_divergence(Q, R_prev, q, avoid_nan=True)
            if df_QR > df_QRprev:
                print(f"    df_QR > df_QRprev")
                print(f"     ├─── df_QR {df_QR:10.5f} df_QRprev {df_QRprev:10.5f}")
                print(f"     └─── Please set `max_iter_inner` larger or `use_prev_theta` True")

        ## For debug
        ## Confirm the ineqality D_f[T, P] < D_f[Q, R]
        if confirm_inequality:
            df_TP = divergence.alpha_divergence(T, P, q, avoid_nan=True)
            df_QR = divergence.alpha_divergence(Q, R, q, avoid_nan=True)
            if df_TP > df_QR:
                print(f"No monotonicity: df_TP {df_TP:10.5f} df_QR {df_QR:10.5f}")

        # argmin D_f[T,P] is equilvant with argmin D_x[P, T]
        # cost = divergence.Tsallis_divergence(P, T, q=q, avoid_nan=True)
        # cost_dual = divergence.Tsallis_divergence(T, P, q=q, avoid_nan=True)
        cost = divergence.alpha_divergence(P, T, q, avoid_nan=True)
        cost_dual = divergence.alpha_divergence(T, P, q, avoid_nan=True)
        elapsed_time = time.time() - start_time
        if verbose and (n_iter % verbose_interval_outer == 0):
            show_verbose(cost, cost_prev, n_iter, elapsed_time, 
                     cost_dual=cost_dual, cost_dual_prev=cost_dual_prev,
                     em_step=True)

        if get_history:
            history["iter"].append( n_iter )
            history["time"].append( elapsed_time )
            history["loss"].append( float(cost) )
        
        if mproject.check_convergence(cost_prev, cost, tol_outer):
            converge = True
            break
        else:
            cost_prev = cost
            cost_dual_prev = cost_dual
            n_iter += 1
            R_prev = R
            if use_prev_theta:
                theta_prev = theta

    show_terminate(converge, n_iter, elapsed_time)

    return P, theta, eta, history


In [101]:
N = 20
T = utils_test.generate_low_rank_tensor( (N,N), 10, seed=None)
#P = np.random.rand(N,N,N)
T = T / np.sum(T)

In [102]:
LP, theta, eta, his = LRA(T, 8, 0.5, method="LBFGS", 
                          verbose_inner=True, 
                          verbose_interval_inner=100, 
                          max_iter_inner=100,
                          max_iter_outer=100, 
                          use_prev_theta=False,
                          tol_outer=1.0e-8);

EM-deformed low-rank approximation
  Deformed rank          : 8
Initializations
  EM-procedure           : random
  M-step                 : uniform
Algorithm settings:
  Optimization method    : LBFGS
  Cost function          : Tsallis divergence
    q (Tsallis param)    : 0.5
Input Tensor Info:
  Shape of input tensor  : (20, 20, 8)
  Size of input tensor   : 3200
  Number of params       : 311
  Size of FIM            : 311 x 311 = 96721
Active Interactions:
 1-body: [[0], [1], [2]]
 2-body: [[0, 2], [1, 2]]
 3-body: []
  ├─ [M-step     0 ] |  0.001s |    1.386527e-02 |    2.182595e-02
  └─ [M-step    15 ] |  0.047s |    4.148964e-03 |    4.784028e-03
[Iter   0] Time:  0.048s    Dual Cost:   3.005496e-02    Prime Cost:    3.005496e-02
  ├─ [M-step     0 ] |  0.001s |    1.072886e-02 |    1.456165e-02
  └─ [M-step    22 ] |  0.047s |    4.389679e-04 |    4.211004e-04
[Iter   1] Time:  0.097s    Dual Cost:   1.501111e-02    Prime Cost:    1.501111e-02
  ├─ [M-step     0 ] |  0.001s | 

In [103]:
LP, theta, eta, his = LRA(T, 8, 0.5, method="LBFGS", 
                          verbose_inner=True, 
                          verbose_interval_inner=100, 
                          max_iter_inner=100,
                          max_iter_outer=100, 
                          use_prev_theta=True,
                          tol_outer=1.0e-8);

EM-deformed low-rank approximation
  Deformed rank          : 8
Initializations
  EM-procedure           : random
  M-step                 : Previous θ
Algorithm settings:
  Optimization method    : LBFGS
  Cost function          : Tsallis divergence
    q (Tsallis param)    : 0.5
Input Tensor Info:
  Shape of input tensor  : (20, 20, 8)
  Size of input tensor   : 3200
  Number of params       : 311
  Size of FIM            : 311 x 311 = 96721
Active Interactions:
 1-body: [[0], [1], [2]]
 2-body: [[0, 2], [1, 2]]
 3-body: []
  ├─ [M-step     0 ] |  0.001s |    1.454428e-02 |    1.899589e-02
  └─ [M-step    12 ] |  0.032s |    5.769824e-03 |    5.711867e-03
[Iter   0] Time:  0.033s    Dual Cost:   9.221944e-02    Prime Cost:    9.221944e-02
  ├─ [M-step     0 ] |  0.003s |    1.381797e-03 |    1.338178e-03
  └─ [M-step     3 ] |  0.043s |    1.357627e-03 |    1.297384e-03
[Iter   1] Time:  0.078s    Dual Cost:   7.802423e-02    Prime Cost:    7.802423e-02
  ├─ [M-step     0 ] |  0.004s

In [66]:
LP, theta, eta, his = LRA(T, 8, 0.5, method="LBFGS", 
                          verbose_inner=True, 
                          verbose_interval_inner=20, 
                          max_iter_inner=200,
                          max_iter_outer=200, 
                          use_prev_theta=True,
                          tol_outer=1.0e-8);

EM-deformed low-rank approximation
  Deformed rank          : 8
Algorithm settings:
  Optimization method    : LBFGS
  Cost function          : Tsallis divergence
    q (Tsallis param)    : 0.5
Input Tensor Info:
  Shape of input tensor  : (20, 20, 8)
  Size of input tensor   : 3200
  Number of params       : 311
  Size of FIM            : 311 x 311 = 96721
Active Interactions:
 1-body: [[0], [1], [2]]
 2-body: [[0, 2], [1, 2]]
 3-body: []
  └─ [M-step     0 ] |  0.001s |    1.099087e-02 |    1.550044e-02
  └─ [M-step    12 ] |  0.030s |    3.042469e-03 |    3.349209e-03
[Iter   0] Time:  0.031s    Dual Cost:   3.188525e-02    Prime Cost:    3.188525e-02
used given theta!
  └─ [M-step     0 ] |  0.004s |    4.136633e-04 |    4.115072e-04
  └─ [M-step    20 ] |  0.038s |    2.335524e-04 |    2.349895e-04
  └─ [M-step    25 ] |  0.051s |    2.304529e-04 |    2.319548e-04
[Iter   1] Time:  0.084s    Dual Cost:   1.394547e-02    Prime Cost:    1.394547e-02
used given theta!
  └─ [M-step   

In [7]:
import numpy as np

# 例: D=2, k=3
Q = np.random.rand(4, 5, 3)
T = np.random.rand(4, 5)
P = np.random.rand(4, 5)

R = Q * (T[..., np.newaxis] / P[..., np.newaxis])

In [8]:
R

array([[[2.46539009e+00, 4.67465659e+00, 2.40160924e+00],
        [2.55183229e+00, 5.10508928e-01, 4.24353784e-01],
        [4.07214181e-01, 1.66599549e-01, 5.15369635e-02],
        [4.95555326e-01, 9.89002078e-02, 1.47019935e-01],
        [3.07375531e+00, 1.23098843e+01, 5.22697757e-01]],

       [[7.40443018e-01, 5.51554184e-01, 6.41587996e-01],
        [2.49868386e+00, 1.89657108e+00, 1.39857302e+00],
        [1.97580383e-01, 2.45445535e-01, 7.44464738e-02],
        [8.91250992e-02, 6.73681848e-01, 1.67147147e-01],
        [3.28794272e-01, 5.01290995e+00, 2.27149607e+00]],

       [[4.30746784e-01, 2.00464920e+00, 1.15974561e-01],
        [2.16902274e-01, 1.02816711e-01, 2.07359464e-01],
        [3.16421331e-02, 3.14483731e-02, 6.35116552e-02],
        [6.57876684e-02, 6.73243788e-01, 3.90871326e-01],
        [8.21082172e+00, 2.78415573e-01, 1.09553488e+01]],

       [[1.61902530e-01, 7.91772012e-01, 1.30641885e-01],
        [5.06211886e+00, 2.48339858e+00, 3.20846722e+00],
        

In [10]:
T = np.random.rand(4,5,4,3)

In [13]:
tensor_shape = np.shape(T) + (3,)

(4, 5, 4, 3, 3)

In [13]:
import math
import itertools

def get_intract_CP(D):
    """
    Generate an interaction specification (intract) that includes:
    - All 1-body interactions
    - Only 2-body interactions between the last axis (D-1) and all others
    - No higher-order interactions

    Parameters
    ----------
    D : int
        Number of dimensions (tensor order)

    Returns
    -------
    intract : list of list of int
        Interaction specification as a list of binary vectors for 1-body to D-body interactions.
        Each entry in the outer list corresponds to d-body interactions (d = 1 to D).
    """
    intract = []

    # 1-body: all active
    intract.append([1] * D)

    # 2-body: activate only those involving the last axis (D-1)
    combs_2 = list(itertools.combinations(range(D), 2))
    intract_2 = [1 if (D - 1) in comb else 0 for comb in combs_2]
    intract.append(intract_2)

    # Higher-order: all inactive
    for d in range(3, D + 1):
        intract.append([0] * math.comb(D, d))

    return intract

In [22]:
tensor_shape = (2,3,4,2,3)
intract_for_CP = get_intract_CP(5)

msk = mask.get_learn_indices(tensor_shape, intract_for_CP)
msk

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 2],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 2],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 0, 2],
       [0, 2, 0, 0, 1],
       [0, 2, 0, 0, 2],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 0, 2],
       [0, 0, 2, 0, 1],
       [0, 0, 2, 0, 2],
       [0, 0, 3, 0, 1],
       [0, 0, 3, 0, 2],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 2]])

In [19]:
get_intract_CP(6)

[[1, 1, 1, 1, 1, 1],
 [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0]]